const assert = require("assert");
const Imports = require("../src/models/imports");
const { mockVscode } = require("./test-setup");

describe("Header Management", () => {
  const defaultHeader = [
    "// Generated by Dart Safe Data Class Generator.",
    "// ignore_for_file: type=lint",
  ];

  beforeEach(() => {
    mockVscode.setSetting("custom.headerLines", defaultHeader);
  });

  it("should include existing header in the range", () => {
    const text = `// Generated by Dart Safe Data Class Generator.
// ignore_for_file: type=lint

import 'dart:convert';

class MyClass {}`;

    const imports = new Imports(text);

    // startAtLine should be 1, because it should look back from line 4 (import)
    // and include the comments on lines 1-2 and blank line 3.
    assert.strictEqual(imports.startAtLine, 1);
    assert.strictEqual(imports.endAtLine, 4);
  });

  it("should update header when settings change without duplication", () => {
    const oldHeader = ["// Old Header line 1", "// Old Header line 2"];
    mockVscode.setSetting("custom.headerLines", oldHeader);

    const text = `// Old Header line 1
// Old Header line 2

import 'dart:convert';

class MyClass {}`;

    const imports = new Imports(text);
    assert.strictEqual(imports.startAtLine, 1);

    // Change settings to new header
    const newHeader = ["// NEW Header line 1", "// NEW Header line 2"];
    mockVscode.setSetting("custom.headerLines", newHeader);

    const formatted = imports.formatted;

    // Formatted output should start with NEW header
    assert.ok(
      formatted.startsWith("// NEW Header line 1\n// NEW Header line 2\n"),
    );
    // And should NOT contain the OLD header
    assert.ok(!formatted.includes("Old Header"));
  });

  it("should handle lack of header gracefully", () => {
    const text = `import 'dart:convert';

class MyClass {}`;

    const imports = new Imports(text);
    // Should point to the import line
    assert.strictEqual(imports.startAtLine, 1);

    const formatted = imports.formatted;
    assert.ok(
      formatted.startsWith("// Generated by Dart Safe Data Class Generator."),
    );
  });
});
