// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint, unused_element

import 'package:flutter/material.dart';

// ============================================================================
// ENUMS
// ============================================================================

enum Status { active, inactive, pending, error, success }

enum Priority { low, medium, high, critical }

// ============================================================================
// BASIC CLASS - Primitives and const constructor
// ============================================================================

/// Simple class with primitive types - auto-generates const constructor
@immutable
class User {
  final String name;
  final int age;
  final double rating;
  final bool isActive;
  final num score;

  const User({
    required this.name,
    required this.age,
    this.rating = 0.0,
    this.isActive = true,
    this.score = 0,
  });
}

// ============================================================================
// NULLABLE TYPES
// ============================================================================

/// Class with nullable fields - sentinel pattern for copyWith
class UserProfile {
  final String? bio;
  final int? followers;
  final DateTime? lastLogin;
  final List<String>? tags;

  const UserProfile({
    this.bio,
    this.followers,
    this.lastLogin,
    this.tags,
  });
}

// ============================================================================
// ENUMS
// ============================================================================

/// Class with enum fields - uses byName serialization
class Task {
  final String title;
  final Status status; // enum
  final Priority? priority; // enum

  const Task({
    required this.title,
    required this.status,
    this.priority,
  });
}

// ============================================================================
// COLLECTIONS
// ============================================================================

/// Class with various collection types
class Container {
  final List<String> items;
  final List<int>? numbers;
  final Map<String, dynamic> metadata;
  final Map<String, int>? scores;
  final Set<String> uniqueTags;
  final List<Map<String, dynamic>> nestedData;

  const Container({
    this.items = const [],
    this.numbers,
    this.metadata = const {},
    this.scores,
    this.uniqueTags = const {},
    this.nestedData = const [],
  });
}

// ============================================================================
// CUSTOM TYPES - Built-in support (DateTime, Color, IconData)
// ============================================================================

/// Class with custom types that have built-in serialization
class Event {
  final DateTime createdAt;
  final DateTime? updatedAt;
  final Color primaryColor;
  final Color? secondaryColor;
  final IconData icon;
  final List<DateTime> milestones;
  final List<Color>? palette;

  const Event({
    required this.createdAt,
    this.updatedAt,
    required this.primaryColor,
    this.secondaryColor,
    required this.icon,
    this.milestones = const [],
    this.palette,
  });
}

// ============================================================================
// NESTED OBJECTS
// ============================================================================

/// Simple nested class
class Address {
  final String street;
  final String city;
  final String country;

  const Address({
    required this.street,
    required this.city,
    this.country = 'Unknown',
  });
}

/// Class with nested objects
class Company {
  final String name;
  final Address headquarters;
  final Address? billingAddress;
  final List<Address> branches;
  final List<Address>? partners;

  const Company({
    required this.name,
    required this.headquarters,
    this.billingAddress,
    this.branches = const [],
    this.partners,
  });
}

// ============================================================================
// CUSTOM SERIALIZATION - Using directives
// ============================================================================

/// Class demonstrating custom serialization with directives
/// Use comments: $from: <expression> and $to: <expression>
class CustomSerialization {
  final String id;

  /// Duration stored as milliseconds in JSON
  final Duration
      timeout; // $from: Duration(milliseconds: (map['timeout'] as int?) ?? 0), $to: timeout.inMilliseconds

  /// Uri stored as string in JSON
  final Uri
      endpoint; // $from: Uri.parse(map['endpoint'] as String? ?? ''), $to: endpoint.toString()

  /// Custom date format (Unix timestamp)
  final DateTime
      timestamp; // $from: DateTime.fromMillisecondsSinceEpoch((map['timestamp'] as int?) ?? 0), $to: timestamp.millisecondsSinceEpoch

  const CustomSerialization({
    required this.id,
    required this.timeout,
    required this.endpoint,
    required this.timestamp,
  });
}

// ============================================================================
// CUSTOM TYPE MAPPING - Using global settings
// ============================================================================

/// Custom types defined in extension settings:
/// - DateTime: DateTime.parse(String) <-> toIso8601String()
/// - Color: Color(int) <-> value
/// - IconData: IconData(int) <-> codePoint
/// - Timestamp: pass-through (no conversion)

class FirestoreDocument {
  final String id;
  final DateTime createdAt;
  final Color themeColor;
  // Timestamp passes through without conversion (defined in custom.types)
  // final Timestamp serverTime;

  const FirestoreDocument({
    required this.id,
    required this.createdAt,
    required this.themeColor,
  });
}

// ============================================================================
// GENERICS
// ============================================================================

/// Generic class with type parameter
class Box<T> {
  final T value;
  final String label;

  const Box({
    required this.value,
    this.label = '',
  });
}

/// Class with multiple type parameters
class Pair<K, V> {
  final K key;
  final V value;

  const Pair({
    required this.key,
    required this.value,
  });
}

// ============================================================================
// INHERITANCE
// ============================================================================

/// Abstract base class
abstract class Entity {
  final String id;

  const Entity({required this.id});
}

/// Class extending another
class Product extends Entity {
  final String name;
  final double price;

  const Product({
    required super.id,
    required this.name,
    required this.price,
  });
}

// ============================================================================
// SEALED CLASS - Result pattern (requires sealed.enabled setting)
// ============================================================================

/// Sealed class for Result pattern
/// Enable sealed.enabled setting to auto-generate Success/Failure subclasses
sealed class Result<T, E> {
  const Result();
}

// When sealed.enabled = true, generates:
// final class Success<T, E> extends Result<T, E> {
//   final T data;
//   const Success(this.data);
// }
//
// final class Failure<T, E> extends Result<T, E> {
//   final E error;
//   const Failure(this.error);
// }

// ============================================================================
// COMPLETE EXAMPLE - All features combined
// ============================================================================

/// Comprehensive example showing all generator features
@immutable
class CompleteExample {
  // Primitives
  final String name;
  final int count;
  final double value;
  final bool flag;

  // Nullable primitives
  final String? nickname;
  final int? optionalCount;

  // Enums
  final Status status; // enum
  final Priority? priority; // enum

  // Collections
  final List<String> tags;
  final Map<String, int> scores;
  final Set<String>? categories;

  // Custom types (built-in support)
  final DateTime createdAt;
  final Color themeColor;
  final IconData icon;

  // Nullable custom types
  final DateTime? modifiedAt;
  final Color? accentColor;

  // Nested objects
  final Address address;
  final Address? shippingAddress;
  final List<Address> locations;

  // Collections of custom types
  final List<DateTime> history;
  final List<Color>? colorScheme;

  // Custom serialization
  final Duration
      timeout; // $from: Duration(milliseconds: (map['timeout'] as int?) ?? 1000), $to: timeout.inMilliseconds
  final Uri
      apiUrl; // $from: Uri.parse(map['api_url'] as String? ?? 'https://api.example.com'), $to: apiUrl.toString()

  const CompleteExample({
    required this.name,
    this.count = 0,
    this.value = 0.0,
    this.flag = false,
    this.nickname,
    this.optionalCount,
    required this.status,
    this.priority,
    this.tags = const [],
    this.scores = const {},
    this.categories,
    required this.createdAt,
    required this.themeColor,
    required this.icon,
    this.modifiedAt,
    this.accentColor,
    required this.address,
    this.shippingAddress,
    this.locations = const [],
    this.history = const [],
    this.colorScheme,
    required this.timeout,
    required this.apiUrl,
  });
}

// ============================================================================
// IGNORE DIRECTIVE - Skip specific fields
// ============================================================================

/// Use 'ignore' directive to skip serialization for specific fields
class PartialSerialization {
  final String id;
  final String name;
  final String
      cachedValue; // ignore - will be passed through without conversion

  const PartialSerialization({
    required this.id,
    required this.name,
    required this.cachedValue,
  });
}
