// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint, deprecated_member_use
import 'dart:convert';

import 'package:collection/collection.dart';
import 'package:flutter/material.dart';

enum Status {
  active,
  inactive,
  unknown,
  pending,
  loading,
  error,
  success,
  disabled,
  cancelled,
  expired,
}

@immutable
class Types {
  final int? age;
  final num radius;
  final double height;
  final bool? isPremium;
  final Status status; // enum
  final Status? lastStatus; // enum
  final String name;
  final List<String> names;
  final Map<String, int>? info;
  final List<Map<String, dynamic>> objects;
  final Color color;
  final List<Color>? colors;
  final DateTime? date;
  final List<DateTime> dates;
  final IconData icon;
  final List<IconData>? icons;
  final AnotherClass? another;
  final List<AnotherClass> anothers;
  final List<AnotherClass>? noOthers;
  const Types({
    this.age,
    this.radius = 0,
    this.height = 0.0,
    this.isPremium,
    required this.status,
    this.lastStatus,
    this.name = '',
    this.names = const [],
    this.info,
    this.objects = const [],
    required this.color,
    this.colors,
    this.date,
    this.dates = const [],
    required this.icon,
    this.icons,
    this.another,
    this.anothers = const [],
    this.noOthers,
  });

  static const Object _sentinel = Object();
  Types copyWith({
    Object? age = _sentinel,
    num? radius,
    double? height,
    Object? isPremium = _sentinel,
    Status? status,
    Object? lastStatus = _sentinel,
    String? name,
    List<String>? names,
    Object? info = _sentinel,
    List<Map<String, dynamic>>? objects,
    Color? color,
    Object? colors = _sentinel,
    Object? date = _sentinel,
    List<DateTime>? dates,
    IconData? icon,
    Object? icons = _sentinel,
    Object? another = _sentinel,
    List<AnotherClass>? anothers,
    Object? noOthers = _sentinel,
  }) {
    return Types(
      age: age == _sentinel ? this.age : (age as int?),
      radius: radius ?? this.radius,
      height: height ?? this.height,
      isPremium: isPremium == _sentinel ? this.isPremium : (isPremium as bool?),
      status: status ?? this.status,
      lastStatus:
          lastStatus == _sentinel ? this.lastStatus : (lastStatus as Status?),
      name: name ?? this.name,
      names: names ?? this.names,
      info: info == _sentinel ? this.info : (info as Map<String, int>?),
      objects: objects ?? this.objects,
      color: color ?? this.color,
      colors: colors == _sentinel ? this.colors : (colors as List<Color>?),
      date: date == _sentinel ? this.date : (date as DateTime?),
      dates: dates ?? this.dates,
      icon: icon ?? this.icon,
      icons: icons == _sentinel ? this.icons : (icons as List<IconData>?),
      another: another == _sentinel ? this.another : (another as AnotherClass?),
      anothers: anothers ?? this.anothers,
      noOthers: noOthers == _sentinel
          ? this.noOthers
          : (noOthers as List<AnotherClass>?),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'age': age,
      'radius': radius,
      'height': height,
      'is_premium': isPremium,
      'status': status.name,
      'last_status': lastStatus?.name,
      'name': name,
      'names': names,
      'info': info,
      'objects': objects,
      'color': color.value,
      'colors': colors?.map((x) => x.value).toList(),
      'date': date?.toIso8601String(),
      'dates': dates.map((x) => x.toIso8601String()).toList(),
      'icon': icon.codePoint,
      'icons': icons?.map((x) => x.codePoint).toList(),
      'another': another?.toMap(),
      'anothers': anothers.map((x) => x.toMap()).toList(),
      'no_others': noOthers?.map((x) => x.toMap()).toList(),
    };
  }

  factory Types.fromMap(Map<String, dynamic> map) {
    T cast<T>(String k) => map[k] is T
        ? map[k] as T
        : throw ArgumentError.value(map[k], k, '$T ← ${map[k].runtimeType}');
    return Types(
      age: cast<num?>('age')?.toInt(),
      radius: cast<num?>('radius') ?? 0,
      height: cast<num?>('height')?.toDouble() ?? 0.0,
      isPremium: cast<bool?>('is_premium'),
      status: Status.values
          .byName(cast<String?>('status') ?? Status.values.first.name),
      lastStatus: map['last_status'] != null
          ? Status.values
              .byName(cast<String?>('last_status') ?? Status.values.first.name)
          : null,
      name: cast<String?>('name') ?? '',
      names: List<String>.from(cast<Iterable?>('names') ?? const <String>[]),
      info:
          map['info'] != null ? Map<String, int>.from(cast<Map>('info')) : null,
      objects: List<Map<String, dynamic>>.from(cast<Iterable?>('objects')
              ?.map((x) => Map<String, dynamic>.from(x as Map)) ??
          const <Map<String, dynamic>>[]),
      color: Color(cast<int>('color')),
      colors: map['colors'] != null
          ? List<Color>.from(cast<Iterable>('colors')
              .map((x) => Color((x as num?)?.toInt() ?? 0)))
          : null,
      date: map['date'] != null ? DateTime.parse(cast<String>('date')) : null,
      dates: List<DateTime>.from(cast<Iterable?>('dates')
              ?.map((x) => DateTime.parse(x as String? ?? '')) ??
          const <DateTime>[]),
      icon: IconData(cast<int>('icon')),
      icons: map['icons'] != null
          ? List<IconData>.from(cast<Iterable>('icons')
              .map((x) => IconData((x as num?)?.toInt() ?? 0)))
          : null,
      another: map['another'] != null
          ? AnotherClass.fromMap(Map.from(cast<Map>('another')))
          : null,
      anothers: List<AnotherClass>.from(cast<Iterable?>('anothers')
              ?.map((x) => AnotherClass.fromMap(Map.from(x as Map))) ??
          const <AnotherClass>[]),
      noOthers: map['no_others'] != null
          ? List<AnotherClass>.from(cast<Iterable>('no_others')
              .map((x) => AnotherClass.fromMap(Map.from(x as Map))))
          : null,
    );
  }

  String toJson() => json.encode(toMap());

  factory Types.fromJson(String source) =>
      Types.fromMap(json.decode(source) as Map<String, dynamic>);

  @override
  String toString() {
    return '''Types(
      age: $age,
      radius: $radius,
      height: $height,
      isPremium: $isPremium,
      status: $status,
      lastStatus: $lastStatus,
      name: $name,
      names: $names,
      info: $info,
      objects: $objects,
      color: $color,
      colors: $colors,
      date: $date,
      dates: $dates,
      icon: $icon,
      icons: $icons,
      another: $another,
      anothers: $anothers,
      noOthers: $noOthers
      )''';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    final collectionEquals = const DeepCollectionEquality().equals;

    return other is Types &&
        other.age == age &&
        other.radius == radius &&
        other.height == height &&
        other.isPremium == isPremium &&
        other.status == status &&
        other.lastStatus == lastStatus &&
        other.name == name &&
        collectionEquals(other.names, names) &&
        collectionEquals(other.info, info) &&
        collectionEquals(other.objects, objects) &&
        other.color == color &&
        collectionEquals(other.colors, colors) &&
        other.date == date &&
        collectionEquals(other.dates, dates) &&
        other.icon == icon &&
        collectionEquals(other.icons, icons) &&
        other.another == another &&
        collectionEquals(other.anothers, anothers) &&
        collectionEquals(other.noOthers, noOthers);
  }

  @override
  int get hashCode {
    return Object.hash(
        age,
        radius,
        height,
        isPremium,
        status,
        lastStatus,
        name,
        names,
        info,
        objects,
        color,
        colors,
        date,
        dates,
        icon,
        icons,
        another,
        anothers,
        noOthers);
  }
}

@immutable
class AnotherClass {
  final String id;
  const AnotherClass({
    this.id = '',
  });

  AnotherClass copyWith({
    String? id,
  }) {
    return AnotherClass(
      id: id ?? this.id,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
    };
  }

  factory AnotherClass.fromMap(Map<String, dynamic> map) {
    T cast<T>(String k) => map[k] is T
        ? map[k] as T
        : throw ArgumentError.value(map[k], k, '$T ← ${map[k].runtimeType}');
    return AnotherClass(
      id: cast<String?>('id') ?? '',
    );
  }

  String toJson() => json.encode(toMap());

  factory AnotherClass.fromJson(String source) =>
      AnotherClass.fromMap(json.decode(source) as Map<String, dynamic>);

  @override
  String toString() => '''AnotherClass(
      id: $id
      )''';

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is AnotherClass && other.id == id;
  }

  @override
  int get hashCode => id.hashCode;
}
