// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint

import 'dart:convert';

import 'package:collection/collection.dart';
import 'package:flutter/material.dart';

// ============================================================================
// ENUMS
// ============================================================================

enum Status { active, inactive, pending, error, success }

enum Priority { low, medium, high, critical }

// ============================================================================
// BASIC CLASS - Primitives and const constructor
// ============================================================================

/// Simple class with primitive types - auto-generates const constructor
@immutable
class User {
  final String name;
  final int age;
  final double rating;
  final bool isActive;
  final num score;

  const User({
    required this.name,
    required this.age,
    this.rating = 0.0,
    this.isActive = true,
    this.score = 0,
  });

  User copyWith({
    String? name,
    int? age,
    double? rating,
    bool? isActive,
    num? score,
  }) {
    return User(
      name: name ?? this.name,
      age: age ?? this.age,
      rating: rating ?? this.rating,
      isActive: isActive ?? this.isActive,
      score: score ?? this.score,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'name': name,
      'age': age,
      'rating': rating,
      'is_active': isActive,
      'score': score,
    };
  }

  factory User.fromMap(Map<String, dynamic> map) {
    T cast<T>(String k) => map[k] is T
        ? map[k] as T
        : throw ArgumentError.value(map[k], k, '$T ← ${map[k].runtimeType}');
    return User(
      name: cast<String?>('name') ?? '',
      age: cast<num?>('age')?.toInt() ?? 0,
      rating: cast<num?>('rating')?.toDouble() ?? 0.0,
      isActive: cast<bool?>('is_active') ?? false,
      score: cast<num?>('score') ?? 0,
    );
  }

  String toJson() => json.encode(toMap());

  factory User.fromJson(String source) =>
      User.fromMap(json.decode(source) as Map<String, dynamic>);

  @override
  String toString() {
    return '''User(
      name: $name,
      age: $age,
      rating: $rating,
      isActive: $isActive,
      score: $score
      )''';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is User &&
        other.name == name &&
        other.age == age &&
        other.rating == rating &&
        other.isActive == isActive &&
        other.score == score;
  }

  @override
  int get hashCode {
    return Object.hash(name, age, rating, isActive, score);
  }
}

// ============================================================================
// NULLABLE TYPES
// ============================================================================

/// Class with nullable fields - sentinel pattern for copyWith
@immutable
class UserProfile {
  final String? bio;
  final int? followers;
  final DateTime? lastLogin;
  final List<String>? tags;

  const UserProfile({
    this.bio,
    this.followers,
    this.lastLogin,
    this.tags,
  });

  static const Object _sentinel = Object();
  UserProfile copyWith({
    Object? bio = _sentinel,
    Object? followers = _sentinel,
    Object? lastLogin = _sentinel,
    Object? tags = _sentinel,
  }) {
    return UserProfile(
      bio: bio == _sentinel ? this.bio : (bio as String?),
      followers: followers == _sentinel ? this.followers : (followers as int?),
      lastLogin:
          lastLogin == _sentinel ? this.lastLogin : (lastLogin as DateTime?),
      tags: tags == _sentinel ? this.tags : (tags as List<String>?),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'bio': bio,
      'followers': followers,
      'last_login': lastLogin?.toIso8601String(),
      'tags': tags,
    };
  }

  factory UserProfile.fromMap(Map<String, dynamic> map) {
    T cast<T>(String k) => map[k] is T
        ? map[k] as T
        : throw ArgumentError.value(map[k], k, '$T ← ${map[k].runtimeType}');
    return UserProfile(
      bio: cast<String?>('bio'),
      followers: cast<num?>('followers')?.toInt(),
      lastLogin: map['last_login'] != null
          ? DateTime.parse(cast<String>('last_login'))
          : null,
      tags: map['tags'] != null
          ? List<String>.from(cast<Iterable<dynamic>>('tags'))
          : null,
    );
  }

  String toJson() => json.encode(toMap());

  factory UserProfile.fromJson(String source) =>
      UserProfile.fromMap(json.decode(source) as Map<String, dynamic>);

  @override
  String toString() {
    return '''UserProfile(
      bio: $bio,
      followers: $followers,
      lastLogin: $lastLogin,
      tags: $tags
      )''';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    final listEquals = const DeepCollectionEquality().equals;

    return other is UserProfile &&
        other.bio == bio &&
        other.followers == followers &&
        other.lastLogin == lastLogin &&
        listEquals(other.tags, tags);
  }

  @override
  int get hashCode {
    return Object.hash(bio, followers, lastLogin, tags);
  }
}

// ============================================================================
// ENUMS
// ============================================================================

/// Class with enum fields - uses byName serialization
@immutable
class Task {
  final String title;
  final Status status; // enum
  final Priority? priority; // enum

  const Task({
    required this.title,
    required this.status,
    this.priority,
  });

  static const Object _sentinel = Object();
  Task copyWith({
    String? title,
    Status? status,
    Object? priority = _sentinel,
  }) {
    return Task(
      title: title ?? this.title,
      status: status ?? this.status,
      priority: priority == _sentinel ? this.priority : (priority as Priority?),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'title': title,
      'status': status.name,
      'priority': priority?.name,
    };
  }

  factory Task.fromMap(Map<String, dynamic> map) {
    T cast<T>(String k) => map[k] is T
        ? map[k] as T
        : throw ArgumentError.value(map[k], k, '$T ← ${map[k].runtimeType}');
    return Task(
      title: cast<String?>('title') ?? '',
      status: Status.values
          .byName(cast<String?>('status') ?? Status.values.first.name),
      priority: map['priority'] != null
          ? Priority.values
              .byName(cast<String?>('priority') ?? Priority.values.first.name)
          : null,
    );
  }

  String toJson() => json.encode(toMap());

  factory Task.fromJson(String source) =>
      Task.fromMap(json.decode(source) as Map<String, dynamic>);

  @override
  String toString() => '''Task(
      title: $title,
      status: $status,
      priority: $priority
      )''';

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is Task &&
        other.title == title &&
        other.status == status &&
        other.priority == priority;
  }

  @override
  int get hashCode => Object.hash(title, status, priority);
}

// ============================================================================
// COLLECTIONS
// ============================================================================

/// Class with various collection types
@immutable
class Container {
  final List<String> items;
  final List<int>? numbers;
  final Map<String, dynamic> metadata;
  final Map<String, int>? scores;
  final Set<String> uniqueTags;
  final List<Map<String, dynamic>> nestedData;

  const Container({
    this.items = const [],
    this.numbers,
    this.metadata = const {},
    this.scores,
    this.uniqueTags = const {},
    this.nestedData = const [],
  });

  static const Object _sentinel = Object();
  Container copyWith({
    List<String>? items,
    Object? numbers = _sentinel,
    Map<String, dynamic>? metadata,
    Object? scores = _sentinel,
    Set<String>? uniqueTags,
    List<Map<String, dynamic>>? nestedData,
  }) {
    return Container(
      items: items ?? this.items,
      numbers: numbers == _sentinel ? this.numbers : (numbers as List<int>?),
      metadata: metadata ?? this.metadata,
      scores: scores == _sentinel ? this.scores : (scores as Map<String, int>?),
      uniqueTags: uniqueTags ?? this.uniqueTags,
      nestedData: nestedData ?? this.nestedData,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'items': items,
      'numbers': numbers,
      'metadata': metadata,
      'scores': scores,
      'unique_tags': uniqueTags.toList(),
      'nested_data': nestedData,
    };
  }

  factory Container.fromMap(Map<String, dynamic> map) {
    T cast<T>(String k) => map[k] is T
        ? map[k] as T
        : throw ArgumentError.value(map[k], k, '$T ← ${map[k].runtimeType}');
    return Container(
      items: List<String>.from(
          cast<Iterable<dynamic>?>('items') ?? const <String>[]),
      numbers: map['numbers'] != null
          ? List<int>.from(cast<Iterable<dynamic>>('numbers'))
          : null,
      metadata: Map<String, dynamic>.from(
          cast<Map<dynamic, dynamic>?>('metadata') ?? const {}),
      scores: map['scores'] != null
          ? Map<String, int>.from(cast<Map<dynamic, dynamic>>('scores'))
          : null,
      uniqueTags: Set<String>.from(
          cast<Iterable<dynamic>?>('unique_tags') ?? const <String>{}),
      nestedData: List<Map<String, dynamic>>.from(
          cast<Iterable<dynamic>?>('nested_data')?.map((x) =>
                  Map<String, dynamic>.from(x as Map<dynamic, dynamic>)) ??
              const <Map<String, dynamic>>[]),
    );
  }

  String toJson() => json.encode(toMap());

  factory Container.fromJson(String source) =>
      Container.fromMap(json.decode(source) as Map<String, dynamic>);

  @override
  String toString() {
    return '''Container(
      items: $items,
      numbers: $numbers,
      metadata: $metadata,
      scores: $scores,
      uniqueTags: $uniqueTags,
      nestedData: $nestedData
      )''';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    final collectionEquals = const DeepCollectionEquality().equals;

    return other is Container &&
        collectionEquals(other.items, items) &&
        collectionEquals(other.numbers, numbers) &&
        collectionEquals(other.metadata, metadata) &&
        collectionEquals(other.scores, scores) &&
        collectionEquals(other.uniqueTags, uniqueTags) &&
        collectionEquals(other.nestedData, nestedData);
  }

  @override
  int get hashCode {
    return Object.hash(
        items, numbers, metadata, scores, uniqueTags, nestedData);
  }
}

// ============================================================================
// CUSTOM TYPES - Built-in support (DateTime, Color, IconData)
// ============================================================================

/// Class with custom types that have built-in serialization
@immutable
class Event {
  final DateTime createdAt;
  final DateTime? updatedAt;
  final Color primaryColor;
  final Color? secondaryColor;
  final IconData icon;
  final List<DateTime> milestones;
  final List<Color>? palette;

  const Event({
    required this.createdAt,
    this.updatedAt,
    required this.primaryColor,
    this.secondaryColor,
    required this.icon,
    this.milestones = const [],
    this.palette,
  });

  static const Object _sentinel = Object();
  Event copyWith({
    DateTime? createdAt,
    Object? updatedAt = _sentinel,
    Color? primaryColor,
    Object? secondaryColor = _sentinel,
    IconData? icon,
    List<DateTime>? milestones,
    Object? palette = _sentinel,
  }) {
    return Event(
      createdAt: createdAt ?? this.createdAt,
      updatedAt:
          updatedAt == _sentinel ? this.updatedAt : (updatedAt as DateTime?),
      primaryColor: primaryColor ?? this.primaryColor,
      secondaryColor: secondaryColor == _sentinel
          ? this.secondaryColor
          : (secondaryColor as Color?),
      icon: icon ?? this.icon,
      milestones: milestones ?? this.milestones,
      palette: palette == _sentinel ? this.palette : (palette as List<Color>?),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt?.toIso8601String(),
      'primary_color': primaryColor.toARGB32(),
      'secondary_color': secondaryColor?.toARGB32(),
      'icon': icon.codePoint,
      'milestones': milestones.map((x) => x.toIso8601String()).toList(),
      'palette': palette?.map((x) => x.toARGB32()).toList(),
    };
  }

  factory Event.fromMap(Map<String, dynamic> map) {
    T cast<T>(String k) => map[k] is T
        ? map[k] as T
        : throw ArgumentError.value(map[k], k, '$T ← ${map[k].runtimeType}');
    return Event(
      createdAt: DateTime.parse(cast<String>('created_at')),
      updatedAt: map['updated_at'] != null
          ? DateTime.parse(cast<String>('updated_at'))
          : null,
      primaryColor: Color(cast<int>('primary_color')),
      secondaryColor: map['secondary_color'] != null
          ? Color(cast<int>('secondary_color'))
          : null,
      icon: IconData(cast<int>('icon')),
      milestones: List<DateTime>.from(cast<Iterable<dynamic>?>('milestones')
              ?.map((x) => DateTime.parse(x as String? ?? '')) ??
          const <DateTime>[]),
      palette: map['palette'] != null
          ? List<Color>.from(cast<Iterable<dynamic>>('palette')
              .map((x) => Color((x as num?)?.toInt() ?? 0)))
          : null,
    );
  }

  String toJson() => json.encode(toMap());

  factory Event.fromJson(String source) =>
      Event.fromMap(json.decode(source) as Map<String, dynamic>);

  @override
  String toString() {
    return '''Event(
      createdAt: $createdAt,
      updatedAt: $updatedAt,
      primaryColor: $primaryColor,
      secondaryColor: $secondaryColor,
      icon: $icon,
      milestones: $milestones,
      palette: $palette
      )''';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    final listEquals = const DeepCollectionEquality().equals;

    return other is Event &&
        other.createdAt == createdAt &&
        other.updatedAt == updatedAt &&
        other.primaryColor == primaryColor &&
        other.secondaryColor == secondaryColor &&
        other.icon == icon &&
        listEquals(other.milestones, milestones) &&
        listEquals(other.palette, palette);
  }

  @override
  int get hashCode {
    return Object.hash(createdAt, updatedAt, primaryColor, secondaryColor, icon,
        milestones, palette);
  }
}

// ============================================================================
// NESTED OBJECTS
// ============================================================================

/// Simple nested class
@immutable
class Address {
  final String street;
  final String city;
  final String country;

  const Address({
    required this.street,
    required this.city,
    this.country = 'Unknown',
  });

  Address copyWith({
    String? street,
    String? city,
    String? country,
  }) {
    return Address(
      street: street ?? this.street,
      city: city ?? this.city,
      country: country ?? this.country,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'street': street,
      'city': city,
      'country': country,
    };
  }

  factory Address.fromMap(Map<String, dynamic> map) {
    T cast<T>(String k) => map[k] is T
        ? map[k] as T
        : throw ArgumentError.value(map[k], k, '$T ← ${map[k].runtimeType}');
    return Address(
      street: cast<String?>('street') ?? '',
      city: cast<String?>('city') ?? '',
      country: cast<String?>('country') ?? '',
    );
  }

  String toJson() => json.encode(toMap());

  factory Address.fromJson(String source) =>
      Address.fromMap(json.decode(source) as Map<String, dynamic>);

  @override
  String toString() => '''Address(
      street: $street,
      city: $city,
      country: $country
      )''';

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is Address &&
        other.street == street &&
        other.city == city &&
        other.country == country;
  }

  @override
  int get hashCode => Object.hash(street, city, country);
}

/// Class with nested objects
@immutable
class Company {
  final String name;
  final Address headquarters;
  final Address? billingAddress;
  final List<Address> branches;
  final List<Address>? partners;

  const Company({
    required this.name,
    required this.headquarters,
    this.billingAddress,
    this.branches = const [],
    this.partners,
  });

  static const Object _sentinel = Object();
  Company copyWith({
    String? name,
    Address? headquarters,
    Object? billingAddress = _sentinel,
    List<Address>? branches,
    Object? partners = _sentinel,
  }) {
    return Company(
      name: name ?? this.name,
      headquarters: headquarters ?? this.headquarters,
      billingAddress: billingAddress == _sentinel
          ? this.billingAddress
          : (billingAddress as Address?),
      branches: branches ?? this.branches,
      partners:
          partners == _sentinel ? this.partners : (partners as List<Address>?),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'name': name,
      'headquarters': headquarters.toMap(),
      'billing_address': billingAddress?.toMap(),
      'branches': branches.map((x) => x.toMap()).toList(),
      'partners': partners?.map((x) => x.toMap()).toList(),
    };
  }

  factory Company.fromMap(Map<String, dynamic> map) {
    T cast<T>(String k) => map[k] is T
        ? map[k] as T
        : throw ArgumentError.value(map[k], k, '$T ← ${map[k].runtimeType}');
    return Company(
      name: cast<String?>('name') ?? '',
      headquarters: Address.fromMap(
          Map.from(cast<Map<dynamic, dynamic>>('headquarters'))),
      billingAddress: map['billing_address'] != null
          ? Address.fromMap(
              Map.from(cast<Map<dynamic, dynamic>>('billing_address')))
          : null,
      branches: List<Address>.from(cast<Iterable<dynamic>?>('branches')?.map(
              (x) => Address.fromMap(Map.from(x as Map<dynamic, dynamic>))) ??
          const <Address>[]),
      partners: map['partners'] != null
          ? List<Address>.from(cast<Iterable<dynamic>>('partners').map(
              (x) => Address.fromMap(Map.from(x as Map<dynamic, dynamic>))))
          : null,
    );
  }

  String toJson() => json.encode(toMap());

  factory Company.fromJson(String source) =>
      Company.fromMap(json.decode(source) as Map<String, dynamic>);

  @override
  String toString() {
    return '''Company(
      name: $name,
      headquarters: $headquarters,
      billingAddress: $billingAddress,
      branches: $branches,
      partners: $partners
      )''';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    final listEquals = const DeepCollectionEquality().equals;

    return other is Company &&
        other.name == name &&
        other.headquarters == headquarters &&
        other.billingAddress == billingAddress &&
        listEquals(other.branches, branches) &&
        listEquals(other.partners, partners);
  }

  @override
  int get hashCode {
    return Object.hash(name, headquarters, billingAddress, branches, partners);
  }
}

// ============================================================================
// CUSTOM SERIALIZATION - Using directives
// ============================================================================

/// Class demonstrating custom serialization with directives
/// Use comments: $from: <expression> and $to: <expression>
@immutable
class CustomSerialization {
  final String id;

  /// Duration stored as milliseconds in JSON
  final Duration
      timeout; // $from: Duration(milliseconds: (map['timeout'] as int?) ?? 0), $to: timeout.inMilliseconds

  /// Uri stored as string in JSON
  final Uri
      endpoint; // $from: Uri.parse(map['endpoint'] as String? ?? ''), $to: endpoint.toString()

  /// Custom date format (Unix timestamp)
  final DateTime
      timestamp; // $from: DateTime.fromMillisecondsSinceEpoch((map['timestamp'] as int?) ?? 0), $to: timestamp.millisecondsSinceEpoch

  const CustomSerialization({
    required this.id,
    required this.timeout,
    required this.endpoint,
    required this.timestamp,
  });

  CustomSerialization copyWith({
    String? id,
    Duration? timeout,
    Uri? endpoint,
    DateTime? timestamp,
  }) {
    return CustomSerialization(
      id: id ?? this.id,
      timeout: timeout ?? this.timeout,
      endpoint: endpoint ?? this.endpoint,
      timestamp: timestamp ?? this.timestamp,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'timeout': timeout.inMilliseconds,
      'endpoint': endpoint.toString(),
      'timestamp': timestamp.millisecondsSinceEpoch,
    };
  }

  factory CustomSerialization.fromMap(Map<String, dynamic> map) {
    T cast<T>(String k) => map[k] is T
        ? map[k] as T
        : throw ArgumentError.value(map[k], k, '$T ← ${map[k].runtimeType}');
    return CustomSerialization(
      id: cast<String?>('id') ?? '',
      timeout: Duration(milliseconds: (map['timeout'] as int?) ?? 0),
      endpoint: Uri.parse(map['endpoint'] as String? ?? ''),
      timestamp:
          DateTime.fromMillisecondsSinceEpoch((map['timestamp'] as int?) ?? 0),
    );
  }

  String toJson() => json.encode(toMap());

  factory CustomSerialization.fromJson(String source) =>
      CustomSerialization.fromMap(json.decode(source) as Map<String, dynamic>);

  @override
  String toString() {
    return '''CustomSerialization(
      id: $id,
      timeout: $timeout,
      endpoint: $endpoint,
      timestamp: $timestamp
      )''';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is CustomSerialization &&
        other.id == id &&
        other.timeout == timeout &&
        other.endpoint == endpoint &&
        other.timestamp == timestamp;
  }

  @override
  int get hashCode {
    return Object.hash(id, timeout, endpoint, timestamp);
  }
}

// ============================================================================
// CUSTOM TYPE MAPPING - Using global settings
// ============================================================================

/// Custom types defined in extension settings:
/// - DateTime: DateTime.parse(String) <-> toIso8601String()
/// - Color: Color(int) <-> value
/// - IconData: IconData(int) <-> codePoint
/// - Timestamp: pass-through (no conversion)

@immutable
class FirestoreDocument {
  final String id;
  final DateTime createdAt;
  final Color themeColor;
  // Timestamp passes through without conversion (defined in custom.types)
  // final Timestamp serverTime;

  const FirestoreDocument({
    required this.id,
    required this.createdAt,
    required this.themeColor,
  });

  FirestoreDocument copyWith({
    String? id,
    DateTime? createdAt,
    Color? themeColor,
  }) {
    return FirestoreDocument(
      id: id ?? this.id,
      createdAt: createdAt ?? this.createdAt,
      themeColor: themeColor ?? this.themeColor,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'created_at': createdAt.toIso8601String(),
      'theme_color': themeColor.toARGB32(),
    };
  }

  factory FirestoreDocument.fromMap(Map<String, dynamic> map) {
    T cast<T>(String k) => map[k] is T
        ? map[k] as T
        : throw ArgumentError.value(map[k], k, '$T ← ${map[k].runtimeType}');
    return FirestoreDocument(
      id: cast<String?>('id') ?? '',
      createdAt: DateTime.parse(cast<String>('created_at')),
      themeColor: Color(cast<int>('theme_color')),
    );
  }

  String toJson() => json.encode(toMap());

  factory FirestoreDocument.fromJson(String source) =>
      FirestoreDocument.fromMap(json.decode(source) as Map<String, dynamic>);

  @override
  String toString() => '''FirestoreDocument(
      id: $id,
      createdAt: $createdAt,
      themeColor: $themeColor
      )''';

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is FirestoreDocument &&
        other.id == id &&
        other.createdAt == createdAt &&
        other.themeColor == themeColor;
  }

  @override
  int get hashCode => Object.hash(id, createdAt, themeColor);
}

// ============================================================================
// GENERICS
// ============================================================================

/// Generic class with type parameter
@immutable
class Box<T> {
  final T value;
  final String label;

  const Box({
    required this.value,
    this.label = '',
  });

  Box<T> copyWith({
    T? value,
    String? label,
  }) {
    return Box<T>(
      value: value ?? this.value,
      label: label ?? this.label,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'value': value,
      'label': label,
    };
  }

  factory Box.fromMap(Map<String, dynamic> map) {
    T cast<T>(String k) => map[k] is T
        ? map[k] as T
        : throw ArgumentError.value(map[k], k, '$T ← ${map[k].runtimeType}');
    return Box<T>(
      value: map['value'] as T,
      label: cast<String?>('label') ?? '',
    );
  }

  String toJson() => json.encode(toMap());

  factory Box.fromJson(String source) =>
      Box.fromMap(json.decode(source) as Map<String, dynamic>);

  @override
  String toString() => '''Box(
      value: $value,
      label: $label
      )''';

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is Box<T> && other.value == value && other.label == label;
  }

  @override
  int get hashCode => Object.hash(value, label);
}

/// Class with multiple type parameters
@immutable
class Pair<K, V> {
  final K key;
  final V value;

  const Pair({
    required this.key,
    required this.value,
  });

  Pair<K, V> copyWith({
    K? key,
    V? value,
  }) {
    return Pair<K, V>(
      key: key ?? this.key,
      value: value ?? this.value,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'key': key,
      'value': value,
    };
  }

  factory Pair.fromMap(Map<String, dynamic> map) {
    return Pair<K, V>(
      key: map['key'] as K,
      value: map['value'] as V,
    );
  }

  String toJson() => json.encode(toMap());

  factory Pair.fromJson(String source) =>
      Pair.fromMap(json.decode(source) as Map<String, dynamic>);

  @override
  String toString() => '''Pair(
      key: $key,
      value: $value
      )''';

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is Pair<K, V> && other.key == key && other.value == value;
  }

  @override
  int get hashCode => Object.hash(key, value);
}

// ============================================================================
// INHERITANCE
// ============================================================================

/// Abstract base class
@immutable
abstract class Entity {
  final String id;

  const Entity({
    this.id = '',
  });

  @override
  String toString() => '''Entity(
      id: $id
      )''';

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is Entity && other.id == id;
  }

  @override
  int get hashCode => id.hashCode;
}

/// Class extending another
@immutable
class Product extends Entity {
  final String name;
  final double price;

  const Product({
    required this.name,
    required this.price,
  });

  Product copyWith({
    String? name,
    double? price,
  }) {
    return Product(
      name: name ?? this.name,
      price: price ?? this.price,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'name': name,
      'price': price,
    };
  }

  factory Product.fromMap(Map<String, dynamic> map) {
    T cast<T>(String k) => map[k] is T
        ? map[k] as T
        : throw ArgumentError.value(map[k], k, '$T ← ${map[k].runtimeType}');
    return Product(
      name: cast<String?>('name') ?? '',
      price: cast<num?>('price')?.toDouble() ?? 0.0,
    );
  }

  String toJson() => json.encode(toMap());

  factory Product.fromJson(String source) =>
      Product.fromMap(json.decode(source) as Map<String, dynamic>);

  @override
  String toString() => '''Product(
      name: $name,
      price: $price
      )''';

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is Product && other.name == name && other.price == price;
  }

  @override
  int get hashCode => Object.hash(name, price);
}

// ============================================================================
// SEALED CLASS - Result pattern (requires sealed.enabled setting)
// ============================================================================

/// Sealed class for Result pattern
/// Enable sealed.enabled setting to auto-generate Success/Failure subclasses
sealed class Result<T, E> {
  const Result();
}

// When sealed.enabled = true, generates:
// final class Success<T, E> extends Result<T, E> {
//   final T data;
//   const Success(this.data);
// }
//
// final class Failure<T, E> extends Result<T, E> {
//   final E error;
//   const Failure(this.error);
// }

// ============================================================================
// COMPLETE EXAMPLE - All features combined
// ============================================================================

/// Comprehensive example showing all generator features
@immutable
class CompleteExample {
  // Primitives
  final String name;
  final int count;
  final double value;
  final bool flag;

  // Nullable primitives
  final String? nickname;
  final int? optionalCount;

  // Enums
  final Status status; // enum
  final Priority? priority; // enum

  // Collections
  final List<String> tags;
  final Map<String, int> scores;
  final Set<String>? categories;

  // Custom types (built-in support)
  final DateTime createdAt;
  final Color themeColor;
  final IconData icon;

  // Nullable custom types
  final DateTime? modifiedAt;
  final Color? accentColor;

  // Nested objects
  final Address address;
  final Address? shippingAddress;
  final List<Address> locations;

  // Collections of custom types
  final List<DateTime> history;
  final List<Color>? colorScheme;

  // Custom serialization
  final Duration
      timeout; // $from: Duration(milliseconds: (map['timeout'] as int?) ?? 1000), $to: timeout.inMilliseconds
  final Uri
      apiUrl; // $from: Uri.parse(map['api_url'] as String? ?? 'https://api.example.com'), $to: apiUrl.toString()

  const CompleteExample({
    required this.name,
    this.count = 0,
    this.value = 0.0,
    this.flag = false,
    this.nickname,
    this.optionalCount,
    required this.status,
    this.priority,
    this.tags = const [],
    this.scores = const {},
    this.categories,
    required this.createdAt,
    required this.themeColor,
    required this.icon,
    this.modifiedAt,
    this.accentColor,
    required this.address,
    this.shippingAddress,
    this.locations = const [],
    this.history = const [],
    this.colorScheme,
    required this.timeout,
    required this.apiUrl,
  });

  static const Object _sentinel = Object();
  CompleteExample copyWith({
    String? name,
    int? count,
    double? value,
    bool? flag,
    Object? nickname = _sentinel,
    Object? optionalCount = _sentinel,
    Status? status,
    Object? priority = _sentinel,
    List<String>? tags,
    Map<String, int>? scores,
    Object? categories = _sentinel,
    DateTime? createdAt,
    Color? themeColor,
    IconData? icon,
    Object? modifiedAt = _sentinel,
    Object? accentColor = _sentinel,
    Address? address,
    Object? shippingAddress = _sentinel,
    List<Address>? locations,
    List<DateTime>? history,
    Object? colorScheme = _sentinel,
    Duration? timeout,
    Uri? apiUrl,
  }) {
    return CompleteExample(
      name: name ?? this.name,
      count: count ?? this.count,
      value: value ?? this.value,
      flag: flag ?? this.flag,
      nickname: nickname == _sentinel ? this.nickname : (nickname as String?),
      optionalCount: optionalCount == _sentinel
          ? this.optionalCount
          : (optionalCount as int?),
      status: status ?? this.status,
      priority: priority == _sentinel ? this.priority : (priority as Priority?),
      tags: tags ?? this.tags,
      scores: scores ?? this.scores,
      categories: categories == _sentinel
          ? this.categories
          : (categories as Set<String>?),
      createdAt: createdAt ?? this.createdAt,
      themeColor: themeColor ?? this.themeColor,
      icon: icon ?? this.icon,
      modifiedAt:
          modifiedAt == _sentinel ? this.modifiedAt : (modifiedAt as DateTime?),
      accentColor:
          accentColor == _sentinel ? this.accentColor : (accentColor as Color?),
      address: address ?? this.address,
      shippingAddress: shippingAddress == _sentinel
          ? this.shippingAddress
          : (shippingAddress as Address?),
      locations: locations ?? this.locations,
      history: history ?? this.history,
      colorScheme: colorScheme == _sentinel
          ? this.colorScheme
          : (colorScheme as List<Color>?),
      timeout: timeout ?? this.timeout,
      apiUrl: apiUrl ?? this.apiUrl,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'name': name,
      'count': count,
      'value': value,
      'flag': flag,
      'nickname': nickname,
      'optional_count': optionalCount,
      'status': status.name,
      'priority': priority?.name,
      'tags': tags,
      'scores': scores,
      'categories': categories?.toList(),
      'created_at': createdAt.toIso8601String(),
      'theme_color': themeColor.toARGB32(),
      'icon': icon.codePoint,
      'modified_at': modifiedAt?.toIso8601String(),
      'accent_color': accentColor?.toARGB32(),
      'address': address.toMap(),
      'shipping_address': shippingAddress?.toMap(),
      'locations': locations.map((x) => x.toMap()).toList(),
      'history': history.map((x) => x.toIso8601String()).toList(),
      'color_scheme': colorScheme?.map((x) => x.toARGB32()).toList(),
      'timeout': timeout.inMilliseconds,
      'api_url': apiUrl.toString(),
    };
  }

  factory CompleteExample.fromMap(Map<String, dynamic> map) {
    T cast<T>(String k) => map[k] is T
        ? map[k] as T
        : throw ArgumentError.value(map[k], k, '$T ← ${map[k].runtimeType}');
    return CompleteExample(
      name: cast<String?>('name') ?? '',
      count: cast<num?>('count')?.toInt() ?? 0,
      value: cast<num?>('value')?.toDouble() ?? 0.0,
      flag: cast<bool?>('flag') ?? false,
      nickname: cast<String?>('nickname'),
      optionalCount: cast<num?>('optional_count')?.toInt(),
      status: Status.values
          .byName(cast<String?>('status') ?? Status.values.first.name),
      priority: map['priority'] != null
          ? Priority.values
              .byName(cast<String?>('priority') ?? Priority.values.first.name)
          : null,
      tags: List<String>.from(
          cast<Iterable<dynamic>?>('tags') ?? const <String>[]),
      scores: Map<String, int>.from(
          cast<Map<dynamic, dynamic>?>('scores') ?? const {}),
      categories: map['categories'] != null
          ? Set<String>.from(cast<Iterable<dynamic>>('categories'))
          : null,
      createdAt: DateTime.parse(cast<String>('created_at')),
      themeColor: Color(cast<int>('theme_color')),
      icon: IconData(cast<int>('icon')),
      modifiedAt: map['modified_at'] != null
          ? DateTime.parse(cast<String>('modified_at'))
          : null,
      accentColor:
          map['accent_color'] != null ? Color(cast<int>('accent_color')) : null,
      address:
          Address.fromMap(Map.from(cast<Map<dynamic, dynamic>>('address'))),
      shippingAddress: map['shipping_address'] != null
          ? Address.fromMap(
              Map.from(cast<Map<dynamic, dynamic>>('shipping_address')))
          : null,
      locations: List<Address>.from(cast<Iterable<dynamic>?>('locations')?.map(
              (x) => Address.fromMap(Map.from(x as Map<dynamic, dynamic>))) ??
          const <Address>[]),
      history: List<DateTime>.from(cast<Iterable<dynamic>?>('history')
              ?.map((x) => DateTime.parse(x as String? ?? '')) ??
          const <DateTime>[]),
      colorScheme: map['color_scheme'] != null
          ? List<Color>.from(cast<Iterable<dynamic>>('color_scheme')
              .map((x) => Color((x as num?)?.toInt() ?? 0)))
          : null,
      timeout: Duration(milliseconds: (map['timeout'] as int?) ?? 1000),
      apiUrl: Uri.parse(map['api_url'] as String? ?? 'https://api.example.com'),
    );
  }

  String toJson() => json.encode(toMap());

  factory CompleteExample.fromJson(String source) =>
      CompleteExample.fromMap(json.decode(source) as Map<String, dynamic>);

  @override
  String toString() {
    return '''CompleteExample(
      name: $name,
      count: $count,
      value: $value,
      flag: $flag,
      nickname: $nickname,
      optionalCount: $optionalCount,
      status: $status,
      priority: $priority,
      tags: $tags,
      scores: $scores,
      categories: $categories,
      createdAt: $createdAt,
      themeColor: $themeColor,
      icon: $icon,
      modifiedAt: $modifiedAt,
      accentColor: $accentColor,
      address: $address,
      shippingAddress: $shippingAddress,
      locations: $locations,
      history: $history,
      colorScheme: $colorScheme,
      timeout: $timeout,
      apiUrl: $apiUrl
      )''';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    final collectionEquals = const DeepCollectionEquality().equals;

    return other is CompleteExample &&
        other.name == name &&
        other.count == count &&
        other.value == value &&
        other.flag == flag &&
        other.nickname == nickname &&
        other.optionalCount == optionalCount &&
        other.status == status &&
        other.priority == priority &&
        collectionEquals(other.tags, tags) &&
        collectionEquals(other.scores, scores) &&
        collectionEquals(other.categories, categories) &&
        other.createdAt == createdAt &&
        other.themeColor == themeColor &&
        other.icon == icon &&
        other.modifiedAt == modifiedAt &&
        other.accentColor == accentColor &&
        other.address == address &&
        other.shippingAddress == shippingAddress &&
        collectionEquals(other.locations, locations) &&
        collectionEquals(other.history, history) &&
        collectionEquals(other.colorScheme, colorScheme) &&
        other.timeout == timeout &&
        other.apiUrl == apiUrl;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      name,
      count,
      value,
      flag,
      nickname,
      optionalCount,
      status,
      priority,
      tags,
      scores,
      categories,
      createdAt,
      themeColor,
      icon,
      modifiedAt,
      accentColor,
      address,
      shippingAddress,
      locations,
      history,
      colorScheme,
      timeout,
      apiUrl,
    ]);
  }
}

// ============================================================================
// IGNORE DIRECTIVE - Skip specific fields
// ============================================================================

/// Use 'ignore' directive to skip serialization for specific fields
@immutable
class PartialSerialization {
  final String id;
  final String name;
  final String
      cachedValue; // ignore - will be passed through without conversion

  const PartialSerialization({
    required this.id,
    required this.name,
    required this.cachedValue,
  });

  PartialSerialization copyWith({
    String? id,
    String? name,
    String? cachedValue,
  }) {
    return PartialSerialization(
      id: id ?? this.id,
      name: name ?? this.name,
      cachedValue: cachedValue ?? this.cachedValue,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'cached_value': cachedValue,
    };
  }

  factory PartialSerialization.fromMap(Map<String, dynamic> map) {
    T cast<T>(String k) => map[k] is T
        ? map[k] as T
        : throw ArgumentError.value(map[k], k, '$T ← ${map[k].runtimeType}');
    return PartialSerialization(
      id: cast<String?>('id') ?? '',
      name: cast<String?>('name') ?? '',
      cachedValue: cast<String?>('cached_value') ?? '',
    );
  }

  String toJson() => json.encode(toMap());

  factory PartialSerialization.fromJson(String source) =>
      PartialSerialization.fromMap(json.decode(source) as Map<String, dynamic>);

  @override
  String toString() => '''PartialSerialization(
      id: $id,
      name: $name,
      cachedValue: $cachedValue
      )''';

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is PartialSerialization &&
        other.id == id &&
        other.name == name &&
        other.cachedValue == cachedValue;
  }

  @override
  int get hashCode => Object.hash(id, name, cachedValue);
}
